"""add index and unique constraint to old_contract_number

Revision ID: 6c5585bdc4cf
Revises: 2ea2b3346116
Create Date: 2026-07-13 07:58:12.444192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5585bdc4cf'
down_revision: Union[str, Sequence[str], None] = '2ea2b3346116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contracts_old_contract_number'), 'contracts', ['old_contract_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_old_contract_number'), table_name='contracts')
    # ### end Alembic commands ###
